version: '2'

volumes:
    database_data:
        driver: local

services:
#########################
# Set up Nginx Container
#########################
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes: 
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php


#########################
# Set up PHP Container
#########################
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html



#########################
# Set up testing Container
#########################
    testing:
        build: ./docker/php/
        volumes_from:
            - php


#########################
# Set up Database (MySQL) container
#########################
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project


